gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/subtyp/subtyp.adb, testsuite/gnat2goto/tests/subtyp/test.out, testsuite/gnat2goto/tests/subtyp/test.py
GNAT does not produce N_Subtype_Indication when no constraint is given, but provides the identifier directly. This fix checks for the type of the subtype indication node, and acts accordingly. Including test case.
=> Fix #19 Subtype indication without constraint

gnat2goto/driver/tree_walk.adb
@hannes-steffenhagen-diffblue Found out that the test I had implemented in in ccdd53f706c1eb6bef21e0c7fdfacf2eca9e89b7 was breaking tests because the test was not narrow enough so it was trivially passing it, marking most integer literals with a width of 64bits when the tests expected a width of 32bits. This fixes it by making the test narrower.
=> Change the test in Do_Constant for the Integer Literal

gnat2goto/driver/ureal_to_binary.adb, gnat2goto/driver/ureal_to_binary.ads, gnat2goto/unit/floating_point_tests.adb, gnat2goto/unit/floating_point_tests.ads, gnat2goto/unit/test_util.adb, gnat2goto/unit/test_util.ads, gnat2goto/unit/unit_tests.adb, gnat2goto/unit_tests.gpr
Adds a `Ureal_To_Binary_IEEE` helper that converts a "universal real" (that is GNAT lingo for rational number represented by a pair of big integers) to an IEEE_Float.
Only tested for 32 bit floats, but that's all we need for now.
Also adds a super basic unit testing framework so we can actually test things like this in isolation.
=> Ureal to binary

gnat2goto/driver/driver.adb, gnat2goto/driver/gnat_utils.adb, gnat2goto/driver/gnat_utils.ads
No longer need to redirect standard_output to json_symtab file.
=> Create and output to <unit_name>.json_symtab

gnat2goto/ireps/irep_specs/code_ifthenelse.json, gnat2goto/ireps/ireps-trivial_sloc.adb, gnat2goto/ireps/ireps_generator.py, testsuite/gnat2goto/tests/func_args/test.out, testsuite/gnat2goto/tests/if_integer/test.out, testsuite/gnat2goto/tests/loops/test.out, testsuite/gnat2goto/tests/main_params_and_return/test.out, testsuite/gnat2goto/tests/mixed_parameters/test.out, testsuite/gnat2goto/tests/out_inout_params/test.out, testsuite/gnat2goto/tests/primitive_pointer/test.opt, testsuite/gnat2goto/tests/proc/test.opt, testsuite/gnat2goto/tests/proc_args/test.opt, testsuite/gnat2goto/tests/ranges/test.opt, testsuite/gnat2goto/tests/record_init/test.opt, testsuite/gnat2goto/tests/recursion/test.opt, testsuite/gnat2goto/tests/subtyp/test.out, testsuite/gnat2goto/tests/two_subprog_bodies/test.opt
This will fix most of the integration tests to work with the latest [external parser support branch of CBMC](https://github.com/NlightNFotis/cbmc/tree/external_parser_support_rebased).
This mostly updates gnat2goto to produce JSON that's more in line with what CBMC expects, and updates test expectations to match changes in CBMC output.
gnat2goto fails with compilation error:
* primitive_pointer (I thought this was a regression, but we've done some investigation and I can't actually find a version of gnat2goto that works with this test)
gnat2goto completes without errors, but cbmc crashes with a segfault upon reading the result (**this is obviously really bad, but I feel like I need to point out again that CBMC doing this is really bad**):
* arrays
* proc
* proc_args
* recursion
gnat2goto …
=> Fix integration tests

gnat2goto/driver/driver.adb, gnat2goto/driver/gnat2goto-options.adb, gnat2goto/driver/gnat2goto-options.ads, gnat2goto/driver/gnat2goto.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/gnat2goto.gpr
If an exception occured during exception handling we'd
halt compilation. With this commit, what we do instead is
report the error and continue on.
The result of the compilation will be ultimately not very useful,
but at least with this we can find out all the places where something
is going wrong rather easily.
For example, with the AdaYaml script we now get output like this:
```
Warning: Subprogram yaml__version_major not in symbol table
Warning: Subprogram yaml__version_minor not in symbol table
Warning: Subprogram yaml__version_patch not in symbol table
N_Use_Type_Clause (Node_Id=2295) (source,analyzed)
Sloc = 8534  yaml.adb:12:4
Subtype_Marks = List (List_Id=-99999978)
Hidden_By_Use_Clause = <no elist>
Used_Operations = (Elist_Id=100000158)
raised PROGRAM_ERROR : tree_walk.adb:3853 …
```
=> Add statement handling exception fallback

.travis.yml
An UOK in the testsuite means that the test was marked as "expected fail" XFAIL
but actually ended up passing. This is something that requires attention,
so reporting a failure in this case is appropriate.
=> Fail testsuite on travis on UOK

gnat2goto/driver/driver.adb, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/ranges/test.opt
Adds Universal_Integer type to symbol table.
Also moves the unsupported feature check to allow universal integer type not to
be in the table during gnat parsing.
=> testsuite/ranges fix [ADA-202]

.travis.yml
This PR builds on #72 and adds a couple of extra improvements:
* Enable the regression tests to output a diff where tests fail due to differing output (rather than a single line saying "DIFF"
* Reduces the amount of CBMC we build, since we don't need to build all of it to be able to run the gnat2goto regression tests
* Add a 60 second timeout per-test. The default time out value is too large (760 seconds) which causes a hanging test case to then cause Travis to timeout the entire job.
Only the final two commits need to be reviewed. 
NOTE: This should not be merged until #72 has been merged
=> Improvements to gnat2goto CI

.travis.yml
NOTE, this builds on PR #75 so only the final commit in this PR is for review, and this PR will need rebasing once #75 is merged.
=> Turn on gnat python color output for regression test results in CI

.travis.yml, testsuite/gnat2goto/tests/assign/test.opt, testsuite/gnat2goto/tests/floating_point_literals/test.opt, testsuite/gnat2goto/tests/func/test.opt, testsuite/gnat2goto/tests/func_args/test.opt, testsuite/gnat2goto/tests/if_integer/test.opt, testsuite/gnat2goto/tests/ifthenelse/test.opt, testsuite/gnat2goto/tests/long_integer/test.opt, testsuite/gnat2goto/tests/loops/test.opt, testsuite/gnat2goto/tests/main_params_and_return/test.opt, testsuite/gnat2goto/tests/mixed_parameters/test.opt, testsuite/gnat2goto/tests/out_inout_params/test.opt, testsuite/gnat2goto/tests/pragmas/test.opt, testsuite/gnat2goto/tests/records/test.opt, testsuite/gnat2goto/tests/subtyp/test.opt, testsuite/gnat2goto/tests/whileloop/test.opt
These tests are failing since we switched CI to use cbmc/develop - we are actively working on fixing these regression tests, but in the meantime lets XFAIL them so that we have green CI and don't have to rely on admin rights to force merging of changes.
=> XFAIL failing regression tests while we work on getting this working

.travis.yml, testsuite/gnat2goto/testsuite.py
This change to testsuite.py means we no longer need to have the fragile grep'ing of the output to indicate to travis whether any regression tests failed or not.
=> Make testsuite.py return a fail code when any regression test fails

gnat2goto/driver/binary_to_hex.adb, gnat2goto/unit/binary_to_hex_tests.adb
CBMC expects bitvectors in hexadecimal format to be uppercase
=> Make hex bitvector output uppercase

gnat2goto/driver/driver.adb, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/follow.adb, gnat2goto/ireps/ireps-follow_irep.adb, gnat2goto/ireps/ireps_generator.py, testsuite/gnat2goto/tests/primitive_pointer/test.opt, testsuite/gnat2goto/tests/primitive_pointer/test.out
In `driver.adb` call `Follow_Irep` on every symbol in symbol table.
In `ireps_generator.py` reuse `To_JSON` to implement `Follow_Irep`: traverse the irep tree to follow `I_Symbol_Type` nodes. The irep table is not modified: we only change what ireps are referred to in some node (of the irep tree).
=> Implement namespace.follow for symbol types

gnat2goto/driver/binary_to_hex.adb, gnat2goto/driver/binary_to_hex.ads, gnat2goto/unit/binary_to_hex_tests.adb, testsuite/gnat2goto/tests/primitive_pointer/primitive_pointer.adb
CBMC expects hex bitvectors to not have leading zeroes.
=> Strip leading zeroes from hex bitvector output

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/record_init/test.opt
This contains the changes from #98 that are changing the behaviour of gnat2goto. This is to make #98 easier to review, as to isolate in it only the changes that were done in the test suite. After this gets merged, then #98 will be rebased on top of `master`.
This is fixing a particular issue with how a `for` loop in gnat2goto was getting constructed and how it was interacting with the transfer (casting) functions in CBMC. It was creating the following (pseudo)code:
```
int decl;
decl = (some int);
for (/* here is the problem, this is empty */; decl < array_length; decl++)
{body}
```
The problem with that the CBMC's [to_code_fort](https://github.com/diffblue/cbmc/blob/9129e09d093f55299bc540da42fc6568b0363483/src/util/std_code.h#L971) is doing a precondition check for 4 operands, and the …
=> Fix an for statement initialisation and improve record_init test

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/recursion/recursion.adb, testsuite/gnat2goto/tests/recursion/test.opt, testsuite/gnat2goto/tests/recursion/test.out
This contains the changes from #98 that are changing the behaviour of gnat2goto. This is to make #98 easier to review, as to isolate in it only the changes that were done in the test suite. After this gets merged, then #98 will be rebased on top of `master`.
=> Fix LHS assignment in Do_Procedure_Call_Statement and Fix the recursion

gnat2goto/driver/driver.adb, testsuite/gnat2goto/tests/boolean_type/boolean_type.adb, testsuite/gnat2goto/tests/boolean_type/test.out, testsuite/gnat2goto/tests/boolean_type/test.py
The way we represent Ada Standard True / False is (similar to how we
represent enums) having them be global variables. So far unfortunately
there was no code initialising them, so things like
```
pragma Assert (True)
```
would, confusingly, lead to cbmc assertion failures. This fixes that by
initialising `standard__boolean__{true,false}` in `__CPROVER__start`
=> Initialize ada true/false variables

testsuite/gnat2goto/tests/abs/absolute.adb, testsuite/gnat2goto/tests/abs/test.opt, testsuite/gnat2goto/tests/abs/test.py
We don't have an implementation for computing absolute values (as an in-built
operator). Fix will probably require building a new function (in C) that
implements it and returning a function call.
=> Add failing test for operator abs

testsuite/gnat2goto/tests/lhs_op_or/lhs_op_or.adb, testsuite/gnat2goto/tests/lhs_op_or/test.opt, testsuite/gnat2goto/tests/lhs_op_or/test.py
Or (and other logical operators) is not binary (or at least it's irep isn't): we
can't simply set the lhs. We will probably need to handle the n-ary operators
separately, appending the lhs and rhs using the append_op setter.
=> Add failing test for or operator

testsuite/gnat2goto/tests/minus/minus.adb, testsuite/gnat2goto/tests/minus/test.opt, testsuite/gnat2goto/tests/minus/test.py
We only support binary minus. There is unary_minus_exprt in CBMC. We may need to
introduce a new irep to be able to use it.
=> Add failing test for unary minus operator

testsuite/gnat2goto/tests/real_literal/real_literal.adb, testsuite/gnat2goto/tests/real_literal/test.opt, testsuite/gnat2goto/tests/real_literal/test.py
We do not support negative denominators which can only happen for real literals
represented with base 0. Small reals are represented with base 2 for which
denominator cannot be negative. I think the check can be safely removed but
perhaps we want to investigate the consequences.
=> Add failing test for funny real literals

testsuite/gnat2goto/tests/process_statement/external_types.ads, testsuite/gnat2goto/tests/process_statement/process_statement.adb, testsuite/gnat2goto/tests/process_statement/test.opt, testsuite/gnat2goto/tests/process_statement/test.py
This new tests only covers N_Renaming_Declaration, N_Block_Statement, and
N_Use_Type_Clause. The first two fail in gnat2goto with warning and the third
fails in CBMC with malformed symbol.
=> Add failing test for unsupported declarations

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/character_literal/character_literal.adb, testsuite/gnat2goto/tests/character_literal/test.opt, testsuite/gnat2goto/tests/character_literal/test.py
We don't support character literals: this needs a new function (similar to
`do_constant`) to be called from `do_expression`.
=> Add failing test for character literals

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/floating_definition/floating_definition.adb, testsuite/gnat2goto/tests/floating_definition/test.opt, testsuite/gnat2goto/tests/floating_definition/test.py
There is no infrastructure for constructing floating point types in gnat2goto.
This PR introduces a simple test to start with and clears the reporting in
`tree_walk` a bit.
=> Add failing test for floating type definition

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/op_and/op_and.adb, testsuite/gnat2goto/tests/op_and/op_and_example.adb, testsuite/gnat2goto/tests/op_and/test.out, testsuite/gnat2goto/tests/op_and/test.py
I started playing around with adding a test for operator `and`, and I noticed we don't support it. Since it's implementation is extremely similar to the `or` operator I implemented yesterday, I figured it wouldn't take me long to implement it.
Without this patch, when we try to run gnat2goto and then cbmc on the result we get this:
```
Standard_Output from gnat2goto op_and:
N_Op_And "Oand" (Node_Id=2293) (source,analyzed)
Parent = N_Pragma_Argument_Association <No_Name> (Node_Id=2329)
Sloc = 8325  op_and.adb:7:20
Chars = "Oand" (Name_Id=300000398)
Left_Opnd = N_Identifier "a" (Node_Id=2290)
Right_Opnd = N_Identifier "b" (Node_Id=2292)
Entity = N_Defining_Identifier "Oand" (Entity_Id=1809s)
Etype = N_Defining_Identifier "boolean" (Entity_Id=16s)
N_Op_And "Oand" (Node_Id=2300) …
```
=> Add support for operator and

testsuite/gnat2goto/lib/python/test_support.py, testsuite/gnat2goto/tests/op_and/test.out
Previously test output could have changed depending on what the OS or
filesystem decided would be appropriate, which could lead to randomly
breaking tests. This makes sure that test cases are always sorted
alphabetically.
Fixes #141
=> Do not depend on file ordering in testsuite

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/op_or/op_or_example.adb, testsuite/gnat2goto/tests/op_or/test.out
Before this change, the operator or had been implemented as the short circuiting operator, which in reality is or else. This fixes the semantics to be closer to the non-short circuiting operator.
=> Fix handling of operator or.

gnat2goto/driver/tree_walk.adb
Instead of having two very similar functions that do the same thing but differ in one line, provide one polymorphic function that calls the appropriate function through a function pointer passed to it. I think this should simplify maintenance in the future.
Also add some documentation.
=> Simplify the two functions that handle or and and operators

gnat2goto/unit/floating_point_tests.adb, gnat2goto/unit/test_util.adb, gnat2goto/unit/test_util.ads
Currently 1.2 and 1.1 get converted to 1.8 instead, this unit test documents and checks for this buggy behaviour.
Also adds a facility to expect test failures for the unit tests.
This is related to https://github.com/diffblue/gnat2goto/pull/148, I also wanted a unit test for the conversion bug that was found in there.
=> Add failing float conversion test

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/abs/absolute.adb, testsuite/gnat2goto/tests/abs/absolute_float.adb, testsuite/gnat2goto/tests/abs/test.opt, testsuite/gnat2goto/tests/abs/test.out
Also changes the abs test slightly to make sure we're testing runtime behavior
rather than the constant propagator.
=> Implement Op_Abs

gnat2goto/driver/binary_to_hex.adb, gnat2goto/driver/binary_to_hex.ads, gnat2goto/driver/driver.adb, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/range_check.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/driver/ureal_to_binary.adb, gnat2goto/driver/ureal_to_binary.ads, gnat2goto/ireps/irep_specs/bounded_floatbv_type.json, gnat2goto/ireps/ireps_generator.py, gnat2goto/unit/floating_point_tests.adb, testsuite/gnat2goto/tests/floating_definition/floating_definition.adb, testsuite/gnat2goto/tests/floating_definition/test.opt, testsuite/gnat2goto/tests/floating_definition/test.out, testsuite/gnat2goto/tests/floating_point_literals/floating_point_literals.adb, testsuite/gnat2goto/tests/floating_point_literals/test.opt, testsuite/gnat2goto/tests/floating_point_literals/test.out
The type definition may contain ranges so this PR also brings in a new irep spec for bounded floatbv type, conversion to regular floatbv type, storage for real bounds, etc. We also found a bug in the conversion and demonstrate it via a modified test.
=> Introduce floating point type definition

testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/Use_Type_Clause.adb, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/count_types.adb, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/count_types.ads, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/external_types.ads, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/test.opt, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/test.out, testsuite/gnat2goto/tests/package_use_type_N_Use_Type_Clause/use_type_clause.adb
NB our package implementation does not support function calls atm, so 
although 'use type' can work fully if only built-in operators are used, 
any use of functions or overloaded operators or new 'basic operations' 
for a custom type will fail.
=> Tests for 'use type' & 'use all type' clause

experiments/list_unsupported.sh
I believe the issue see in https://github.com/martin-cs/ASVAT/issues/33#issuecomment-475199120 is probably due to a piece of Bash syntax in the Posix SH script. This PR removes that Bash syntax in favour of pure Posix SH syntax.
=> Remove a bash-ism to ensure script is posix compliant

testsuite/gnat2goto/tests/arrays_declaration_failure1/arrays_declaration_failure1.adb, testsuite/gnat2goto/tests/arrays_declaration_failure1/test.opt, testsuite/gnat2goto/tests/arrays_declaration_failure1/test.py, testsuite/gnat2goto/tests/arrays_declaration_failure2/arrays_declaration_failure2.adb, testsuite/gnat2goto/tests/arrays_declaration_failure2/test.opt, testsuite/gnat2goto/tests/arrays_declaration_failure2/test.py
Key purpose of this PR is to document a way of declaring arrays that causes errors. This also happens for multidimensional arrays (#176).
Potentially independent failure modes are in separate tests - for clarity and ease of debugging.
=> tests for newly found array declaration failure modes

testsuite/gnat2goto/tests/string_equality/string_equality.adb, testsuite/gnat2goto/tests/string_equality/test.opt, testsuite/gnat2goto/tests/string_equality/test.py
During implementation of the case_statement #171 , while authoring some tests for that, I found out that the tests were misbehaving because of our partial support for strings. This wasn't covered by any of the tests already existing, so I added one for documentation.
=> Add XFAIL test to demonstrate issues with our string handling

gnat2goto/driver/tree_walk.adb, gnat2goto/driver/tree_walk.ads, testsuite/gnat2goto/tests/type_modular/modular.adb, testsuite/gnat2goto/tests/type_modular/test.out, testsuite/gnat2goto/tests/type_modular/test.py
Adds initial support for modular types. If the boundary is a power of 2 we can
represent the mod type as an unsignedbv without any special handling, but the
boundary value wouldn't fit into that unsignedbv, hence why we're handling this
case specially. The "not power of 2" case requires special arithmetic operators
and explicit tracking of the boundary value, which is why it's going to be
handled seperately in the future.
Also adds a helper for reporting unsupported type declarations.
=> Feature modular type with power of two boundary

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb
Especially do_full_type_declaration didn't like working with a non-type. Also highlights the fact that access types are still unsupported.
=> Return nil type where type is expected [ADA-273]

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/irep_specs/ada_mod_type.json, testsuite/gnat2goto/tests/type_modular_non_power_of_two_decl/modular_type.adb, testsuite/gnat2goto/tests/type_modular_non_power_of_two_decl/test.out, testsuite/gnat2goto/tests/type_modular_non_power_of_two_decl/test.py
This allows us to represent modular types with non-power-of 2
boundaries.
Note: No actual runtime support for any of the operators yet, we will
do this by adding our own implementations and rewriting ada-mod-type to
unsignedbv in a postprocessing step before writing the symbol table.
Also note:
I have no idea how or why the tests pass, considering this isn't actually
replacing the type with something CBMC could be reasonable expected to handle
yet, but I'll take it.
=> Add support for mod type with arbitrary boundaries

gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/gnat2goto_itypes.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/driver/tree_walk.ads
Utility functions (all but two) are made explicit via use of private.
This also clarifies the difference and similarities between our Gnat2goto_Itype
package and the Itype package that is part of Gnat.
There is a good chance that our gnat2goto Itype functions will need extending -
this helps and also clarifies our fundamental types and its implementation (at a
glance, in one place).
Not least - a critical module of the gnat2goto architecture becomes visible -
because it now has its own package.
=> Move do_Itype_xxx functions into own package Gnat2goto_Itypes

gnat2goto/driver/driver.adb, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb
This enforces appropriate initialisation for these two types
[For I : I_Signedbv_Type, then Set_Subtype (I, Make_Nil_Type) ] for signed int
and no subtype initialisation for int.
This removes the use of 'Make_Signedbv_Type (Ireps.Empty, 32)' for an int,
and Make_Signedbv_Type (Make_Nil_Type, 32)) for a signed int.
-----------------------------
NB If 'Make_Int_Type is replaced with 'Make_Signed_Int' type in
Add_CProver_Internal_Symbols, then the following error occurs (always in the
arrays tests):
+Error from cbmc arrays_access:
+file <built-in-additions> line 21: error: conflicting types for variable `__CPROVER_rounding_mode'
+old definition in module `'
+int
+new definition in module `<built-in-library>' file <built-in-additions> line 21
+signed int
=> Replace Make_Signedbv with Make_Signedint and Make_Int

gnat2goto/driver/driver.adb, gnat2goto/ireps/ireps-remove_extra_type_information.adb, gnat2goto/ireps/ireps_generator.py
For some reason CBMC seems to be able to handle the Ada mod type well enough,
but there is no particular reason to keep the ada-specific irep around, we
really only use it to keep track of type information we don't need at 'runtime'.
Note that this is done by just expanding the scope of the existing `Remove_Bounds` function and appropriately renaming it, I figured it'd make more sense to do it this way considering it was doing more or less the same thing.
=> Replace mod type with unsignedbv before writing JSON symtab

experiments/golden-results/UKNI-Information-Barrier-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/type_modular_bitwise/modular_type.adb, testsuite/gnat2goto/tests/type_modular_bitwise/test.out, testsuite/gnat2goto/tests/type_modular_bitwise/test.py
Implementation of `and`, `or`, `xor`, and `not` for modular types. The behaviour of `not` is somewhat surprising but according to the Ada standards. Adds a regression tests.
Please do not review the first commit here: it's a squash of the prerequisite PR #203.
=> Modular arithmetic bitwise operators

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/arrays.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/arrays_attributes_dynamic/array_attributes_dynamic.adb, testsuite/gnat2goto/tests/arrays_attributes_dynamic/test.out, testsuite/gnat2goto/tests/arrays_attributes_dynamic/test.py, testsuite/gnat2goto/tests/arrays_attributes_static/arrays_attributes_static.adb, testsuite/gnat2goto/tests/arrays_attributes_static/test.out, testsuite/gnat2goto/tests/arrays_attributes_static/test.py, testsuite/gnat2goto/tests/arrays_range/arrays_range.adb, testsuite/gnat2goto/tests/arrays_range/test.opt, testsuite/gnat2goto/tests/arrays_range/test.py, testsuite/gnat2goto/tests/in_expression/in_expression.adb, testsuite/gnat2goto/tests/in_expression/test.opt, testsuite/gnat2goto/tests/in_expression/test.py
As far as I could find there are only 4 array attributes and they all work for static arrays (at least to the extend of the added test). For dynamic arrays, this PR adds support for `first` and `last` (length worked before). `Range` for dynamic is still unsupported.
I also include test for `in_expression` that uses range-attribute but fails since we do not support `n_in`.
=> Array attributes first and last

gnat2goto/ireps/ireps-append.adb
Previously this used a pointer into the list table. This leads to undefined
behaviour if the subsequent append operation leads to an allocation of the
table.
=> Fix undefined behavior in Irep_List append

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/range_check.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/arrays_range/arrays_range.adb, testsuite/gnat2goto/tests/arrays_range/test.opt, testsuite/gnat2goto/tests/arrays_range/test.out, testsuite/gnat2goto/tests/dynamic_range_variable/dynamic_range_variable.adb, testsuite/gnat2goto/tests/dynamic_range_variable/test.opt, testsuite/gnat2goto/tests/dynamic_range_variable/test.py, testsuite/gnat2goto/tests/loop_array_range/loop_array_range.adb, testsuite/gnat2goto/tests/loop_array_range/test.opt, testsuite/gnat2goto/tests/loop_array_range/test.py, testsuite/gnat2goto/tests/ranges/test.out
Works for using `'range` to define a subtype. Does not work for dynamic type ranges in general. Failing tests show the scope.
=> Array attribute range support

experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/qualified_expression/qualified_expr.adb, testsuite/gnat2goto/tests/qualified_expression/test.out, testsuite/gnat2goto/tests/qualified_expression/test.py
Add support for qualified expressions. They look like this:
```ada
type MASK is (FIX, DEC, EXP, SIGNIF);
type CODE is (FIX, CLA, DEC, TNZ, SUB); 
PRINT (MASK'(DEC));  --  DEC is of type MASK
PRINT (CODE'(DEC));  --  DEC is of type CODE 
```
=> Add support for qualified expressions

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/arrays.ads, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/op_expon_mod/op_mod_expon.adb, testsuite/gnat2goto/tests/op_expon_mod/test.out, testsuite/gnat2goto/tests/op_expon_mod/test.py
Adds support for the `**` operator for `mod` types, also some more utility functions for creating integer constants and function calls.
Golden results might be out of date, but I don't understand what exactly causes the differences (they seem unrelated to the new functionality?)
=> Feature modular arithmetic expon

testsuite/gnat2goto/tests/private_type_dec_abstract/private_dec_abstract.adb, testsuite/gnat2goto/tests/private_type_dec_abstract/private_dec_abstract.ads, testsuite/gnat2goto/tests/private_type_dec_abstract/test.opt, testsuite/gnat2goto/tests/private_type_dec_abstract/test.py, testsuite/gnat2goto/tests/private_type_dec_array/private_dec_array.adb, testsuite/gnat2goto/tests/private_type_dec_array/private_dec_array.ads, testsuite/gnat2goto/tests/private_type_dec_array/test.opt, testsuite/gnat2goto/tests/private_type_dec_array/test.py, testsuite/gnat2goto/tests/private_type_dec_extension/private_dec_extension.adb, testsuite/gnat2goto/tests/private_type_dec_extension/private_dec_extension.ads, testsuite/gnat2goto/tests/private_type_dec_extension/test.opt, testsuite/gnat2goto/tests/private_type_dec_extension/test.py
There are 3 cases in our golden results where we still do not support private type declarations:
1: abstract type declaration
2: using private type as array type
3: private type extension
=> Failing tests for private type declarations

experiments/golden-results/vct-summary.txt
No functional change to any part of the code. This change in golden results
comes from concurrent merges 214 and 217. 217 introduced vct and 214 resolved
some issues regarding pragmas by ignoring some of them.
=> Update golden results

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/driver.adb
Bump CBMC and fix issues arising from it
=> Feature cbmc bump

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/gnat2goto_itypes.ads, gnat2goto/driver/range_check.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/irep_specs/bounded_mod_type.json, gnat2goto/ireps/irep_specs/bounded_unsignedbv_type.json, gnat2goto/ireps/ireps_generator.py, testsuite/gnat2goto/tests/loop_range_mod_type/test.adb, testsuite/gnat2goto/tests/loop_range_mod_type/test.out, testsuite/gnat2goto/tests/loop_range_mod_type/test.py
Adds the initial support for modular subtypes. Operators for the new type are nor included in this PR.
=> Modular subtype

gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb
We were adding into the symbol table in a number of places across `tree_walk`. This PR wraps every access into a helper function in `goto_utils`. Checks that declared objects are present in the symbol table and introduces them otherwise. In the last bit, there is an overlap with #238.
=> Refactor symtab inserts

experiments/golden-results/SPARK-tetris-summary.txt, experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/arrays.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/representation_clause_component_size/test.adb, testsuite/gnat2goto/tests/representation_clause_component_size/test.out, testsuite/gnat2goto/tests/representation_clause_component_size/test.py, testsuite/gnat2goto/tests/representation_clause_component_size_change/test.adb, testsuite/gnat2goto/tests/representation_clause_component_size_change/test.opt, testsuite/gnat2goto/tests/representation_clause_component_size_change/test.py
In this PR we only check that the component size is the same as the width of the related subtype. That seems to be enough for UKNI. There is also a failing regression test that tries the change the component size.
=> Representation clause component size

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb
during `Do_Defining_Identifier`, in the symbol table ,if they are not present already.
=> Store defined symbols

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb
This is a refactor of #230 with updated golden results. Copy of its description:
In Do_Compilation_Unit the return value Unit_Symbol was not set for a package body
To determine a symbol value for a package body a symbol is determined from
its specification and registered in the symbol table.  This required checking for
the package being a child.
Note: The same check may be required for child subprograms!
=> Define package body symbol

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb
Start processing the `System` package.
=> Process system package

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/range_check.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/range_check_non_bounded/test.adb, testsuite/gnat2goto/tests/range_check_non_bounded/test.out, testsuite/gnat2goto/tests/range_check_non_bounded/test.py
Adds support range checking for signed and unsigned bit-vector types. There is a range check as well.
=> Range check for non-bounded numeric types

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/derived_private_type/derived_private_type.adb, testsuite/gnat2goto/tests/derived_private_type/private_type.ads, testsuite/gnat2goto/tests/derived_private_type/test.out, testsuite/gnat2goto/tests/derived_private_type/test.py, testsuite/gnat2goto/tests/derived_types/derived_types.adb, testsuite/gnat2goto/tests/derived_types/test.out, testsuite/gnat2goto/tests/derived_types/test.py
Correct handling of full type declarations which have a derived_type_definition.
The type declarations have to entered into the global symbol table even if they are a derivation of a private type.
Added some tests for derived type declarations.
=> New derived type checks replaces PR #213

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/separate_subprog/p-inc.asu, testsuite/gnat2goto/tests/separate_subprog/p.adb, testsuite/gnat2goto/tests/separate_subprog/test.out, testsuite/gnat2goto/tests/separate_subprog/test.py, testsuite/gnat2goto/tests/separate_subprog_assert_check/p.adb, testsuite/gnat2goto/tests/separate_subprog_assert_check/test.opt, testsuite/gnat2goto/tests/separate_subprog_assert_check/test.out, testsuite/gnat2goto/tests/separate_subprog_assert_check/test.py
UKNI has subprogram_body_stubs.  The changes on this branch facilitate handling of these stubs by gnat2goto.
The test program which has been added to the regression tests for this new feature, P, has an assertion I think should succeed (if overflows are ignored), but it seems at the moment that the assertion fails.  The action of the called subprogram, Inc, does not seem to be considered by cbmc.
Should I mark this with an XFAIL?  If so I think I should have another test without the assertion so that the subprogram_body_stub feature is always tested.
=> Subprogram body stub

experiments/golden-results/SPARK-tetris-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/arrays.adb, testsuite/gnat2goto/tests/arrays_constraints/array_constraints.adb, testsuite/gnat2goto/tests/arrays_constraints/test.out, testsuite/gnat2goto/tests/arrays_constraints/test.py
This change handles array subtypes and declarations constrained by subtype marks and anonymous subtypes.
The changes are related to the subprogram Make_Array_Default_Initialiser.
Note: The subprogram has been changed to handle subtype constraints but not changed to handle multi-dimensional arrays.  The original subprogram did not handle multi-dimensional arrays.  I do not know if that is a deliberate decision to exclude multi-dimensional arrays from the handled features or an oversight?
I can see how to handle multi-dimensional arrays from the front-end perspective but have not tried to understand how they would be modelled in GOTO.
=> Subtype constraint

testsuite/gnat2goto/tests/character_subtype/char_subtype.adb, testsuite/gnat2goto/tests/character_subtype/test.opt, testsuite/gnat2goto/tests/character_subtype/test.out, testsuite/gnat2goto/tests/character_subtype/test.py
Following up from a comment in the subrange_constrain test (aray_constraints) I have added a failing test for a Character subtype
=> Add a failing test for a character subtype

experiments/list_unsupported.sh, experiments/rational-apex.adc
These changes make the script work OK with .1.ada and .2.ada file naming
but at the moment gnat2goto still expects to import from .ads files.
We need to switch gnat2goto mode somehow when --apex is specified to this
script.
=> Add partial support for Rational APEX file naming conventions to list_unsupported.sh

testsuite/gnat2goto/tests/separate_subprog_assert_check/p-inc.asu
In the regression tests added for testing separate subprograms I accidentally missed a file that should have been included.  The missing file was not apparent because of the XFAIL field in the test.opt file.
I only noticed it had not been checked in when I was creating the test case for enumeration out parameters.
Sorry.
=> Added missing file into test separate_subprog_assert_check

testsuite/gnat2goto/tests/enum_out_param/enum_out.adb, testsuite/gnat2goto/tests/enum_out_param/test.opt, testsuite/gnat2goto/tests/enum_out_param/test.out, testsuite/gnat2goto/tests/enum_out_param/test.py
Test currently fails with gnat2goto raising:
SYSTEM.ASSERTIONS.ASSERT_FAILURE : failed precondition from ireps.ads:1875
gnat2goto fails with above precondition failure when translating UKNI/main.adb line 247 which calls a procedure with an enumeration out parameter.  This small test program replicates the same fault.
The problem seems to lie in gnat2goto driver/tree_walk.adb procedure Handle_Parameter.  The function Wrap_Argument is called with a parameter obtained from the call of the function Handle_Enum_Symbol_Members which appears to return the wrong sort of Irep for the function Make_Address_Of called by Wrap_Argument.
=> Add test for enumeration out parameters

experiments/golden-results/UKNI-Information-Barrier-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/address_clause/address_clause.adb, testsuite/gnat2goto/tests/address_clause/test.out, testsuite/gnat2goto/tests/address_clause/test.py, testsuite/gnat2goto/tests/size_integer_and_objects/check_size.adb, testsuite/gnat2goto/tests/size_integer_and_objects/test.opt, testsuite/gnat2goto/tests/size_integer_and_objects/test.out, testsuite/gnat2goto/tests/size_integer_and_objects/test.py, testsuite/gnat2goto/tests/size_mod_type/check_size_mod.adb, testsuite/gnat2goto/tests/size_mod_type/test.out, testsuite/gnat2goto/tests/size_mod_type/test.py
gnat2goto is crashing when an address representation clause is encountered.  The reason is that gnat2goto was assuming that the expression defining the attribute for all representation clauses is an integer literal.  This is certainly not the case for an address clause because a subprogram has to be called to convert the given integer value to a private Address type.
This mod separates out address clauses before the expression is evaluated and reports a missing feature.  No doubt we will have to deal with address clauses in the future when we decide how to represent and perform some sort of analysis on them.
Assuming that the expression defining the value of a Size or Component_Size attribute is an integer_literal is also too restrictive, it can be a static_expression.  I have replaced …
=> Address clause

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, gnat2goto/driver/tree_walk.adb, gnat2goto/driver/tree_walk.ads, testsuite/gnat2goto/tests/in_expression/in_expression.adb, testsuite/gnat2goto/tests/in_expression/test.opt, testsuite/gnat2goto/tests/in_expression/test.out
That is the check that a value `x` is inside a range `<low,high>`. The implementation simply builds a conjunction `x \geq low /\ x \leq high`. Re-enables existing test (changed so that the assertion is failing).
=> Implement handling N_In

gnat2goto/driver/arrays.ads, testsuite/gnat2goto/tests/rhs_array_assign/rhs_array_assign.adb, testsuite/gnat2goto/tests/rhs_array_assign/test.out, testsuite/gnat2goto/tests/rhs_array_assign/test.py
The precondition on RHS_Array_Assign was too strict for all possibilities of a RHS.
This caused an exception to be raised due to a failed precondition at arrays.ads 83.
Relaxed the precondition to Kind (N) in N_Subexpr.
=> Rhs array assign

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/enum_out_param/test.opt
The case when enum-value is used as a out parameter of a function. There already was a test for it, which is now enabled.
=> Fix enum out param

experiments/golden-results/SPARK-tetris-summary.txt, experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, experiments/list_unsupported.sh
Previously, the `list_unsupported.sh` script was ignoring `GNAT BUG DETECTED` output from gnat2goto, and also ignoring any `raised BLAH` exception messages, except for a few random cases where it found them "by accident". This PR adds specific matches/redacting for these.
=> List unsupported gnat bug and exceptions

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/enum_in_param/test.opt
By casting each occurence of `I_C_Enum` to `int`. The first commit is a squash of prerequisites -- no need to review it here.
=> Fix enum in param

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/declaration_use_package/lib.ads, testsuite/gnat2goto/tests/declaration_use_package/test.adb, testsuite/gnat2goto/tests/declaration_use_package/test.out, testsuite/gnat2goto/tests/declaration_use_package/test.py
`use` clauses only do namespace resolution which is already done by the
frontend, no action is required for us in the driver.
=> Ignore N_Use_Package_Clause in Process_Declaration

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb
Sometimes we'd get mod operations on mod types because they collapse to
unsignedbv. This adds a case handler for this.
No test case because while I can observe this happening in our projects I wasn't able to find a small reproducer.
=> Fix "mod of unsupported type" error

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/case_expression_range/test.opt, testsuite/gnat2goto/tests/case_expression_range/test.out, testsuite/gnat2goto/tests/case_statement_range/case_statement_range.adb, testsuite/gnat2goto/tests/case_statement_range/main.adb, testsuite/gnat2goto/tests/case_statement_range/test.opt, testsuite/gnat2goto/tests/case_statement_range/test.out, testsuite/gnat2goto/tests/case_statement_range/test.py
Add support for ranges in case statements and case expressions, and activate the relevant tests.
This adds support for a missing feature needed for UKNI, constructs that look like this:
```ada
case X is
when 0 .. 5  => return 10;
```
=> Support ranges in case statements and case expressions

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/driver.adb, gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/irep_specs/bitvector_type.json, gnat2goto/ireps/irep_specs/pointer_type.json, gnat2goto/ireps/ireps_generator.py, testsuite/gnat2goto/tests/loop_range_variable/test.adb, testsuite/gnat2goto/tests/loop_range_variable/test.out, testsuite/gnat2goto/tests/loop_range_variable/test.py
since these may contain declarations as well. We thus go through the sequence
and call process declaration/statement respectively. These declarations should
be initialised with expression even thought their has-init-expression flag is
set to false.
Also:
1) extend load_bound_in_hex to accept unsigned type
2) typecast assignments (somehow a type with empty subtype is different from a
type without subtype)
3) removing extra type-info in ireps.adb produces integral bv-types with nil
subtypes.
=> Fix handled sequences of statements

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/driver.adb, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/range_check.adb, gnat2goto/driver/tree_walk.adb
`New_Irep`, and generally using the `Set_*` stuff is a nuisance for maintainability, as any change to the allowed and required fields will not be noticed at compile time. This is the first PR among a series of PRs with the goal of purging it from the codebase entirely and eventually removing it.
This is also preparatory work to fix a long standing issue of assertions just having their assertion number and source locations, but no text or human readable condition.
Also adds/changes some utility functions (particularly float format related stuff now gets passed the width of the floating point type directly rather than an Irep which we only use to get the width).
=> Refactor/remove New_Irep from driver.adb

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/arrays.ads, gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/driver/tree_walk.ads, testsuite/gnat2goto/tests/range_over_subtype/test.adb, testsuite/gnat2goto/tests/range_over_subtype/test.out, testsuite/gnat2goto/tests/range_over_subtype/test.py
Note that commits 5,6 are from prerequisite PR #280 -- no need to review them here. On top of #277 I only added a simple case analysis for mod-subtype bounds (7th commit). Now there are no constraint-related issues in UKNI.
=> Rework of subtype constraint

gnat2goto/driver/range_check.adb, testsuite/gnat2goto/tests/arrays_range/test.out, testsuite/gnat2goto/tests/deferred_constant/test.out, testsuite/gnat2goto/tests/floating_definition/test.out, testsuite/gnat2goto/tests/loop_range_mod_type/test.out, testsuite/gnat2goto/tests/loop_range_variable/test.out, testsuite/gnat2goto/tests/qualified_expression/test.out, testsuite/gnat2goto/tests/range_check_non_bounded/test.out, testsuite/gnat2goto/tests/ranges/test.out
Substitute references to `New_Irep` with the appropriately typed constructors.
=> Remove new irep range check

gnat2goto/driver/arrays.adb
Please ignore the first commit, as it's the code from #288. I'll rebase once it gets merged.
=> Remove references to New_Irep from arrays.adb

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb
This makes the function a little bit longer, but makes the control flow a little bit simpler. Also adds `Node_Id` taking overloads to `Do_Operator_Mod` and `Do_Operator_Sub_Mod` (on that note, I think I know why power-of-2 mod types cause problems now)
=> Remove New_Irep from Do_Operator_Simple

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/gnat_utils.adb, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/function_pointer/test.adb, testsuite/gnat2goto/tests/function_pointer/test.out, testsuite/gnat2goto/tests/function_pointer/test.py, testsuite/gnat2goto/tests/procedure_pointer/test.adb, testsuite/gnat2goto/tests/procedure_pointer/test.out, testsuite/gnat2goto/tests/procedure_pointer/test.py
that is handling the access-function-definition node and the case when function-call node is explicit-dereference.
This required some special casing for getting the formal parameter (in gnat-utils) and building the address-of for functions.
A test is included.
=> Add basic support for function pointers

experiments/list_unsupported.sh
This adds a wrapper script that uses the new `build.sh` and `list_unsupported_report.sh` scripts but provides the same interface as the old `list_unsupported.sh` script.
=> Wrapper script to match the old list_unsupported.sh interface

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/goto_utils.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/irep_specs/index_expr.json, testsuite/gnat2goto/tests/basic_exception/test.adb, testsuite/gnat2goto/tests/basic_exception/test.c, testsuite/gnat2goto/tests/basic_exception/test.out, testsuite/gnat2goto/tests/basic_exception/test.py, testsuite/gnat2goto/tests/range_check_exception/test.adb, testsuite/gnat2goto/tests/range_check_exception/test.out, testsuite/gnat2goto/tests/range_check_exception/test.py
Turning: `raise exception` into `assert(false); assume(false);` (wrapped in a nicely named function) and conditioning the handler statements by `false` , i.e.
```
begin
Foo (5);
exception
when My_Favourite_Exception => Destroy_Universe (Now);
end;
```
is translated into
```
Foo(5);
if (0) { Destroy_Universe(Now); }
```
There is a test (3rd commit) and the first commit is from a prerequisite #284 -- no need to review here.
=> Basic exception support

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/no_return/main.adb, testsuite/gnat2goto/tests/no_return/test.out, testsuite/gnat2goto/tests/no_return/test.py, testsuite/gnat2goto/tests/no_return_returns/main.adb, testsuite/gnat2goto/tests/no_return_returns/test.out, testsuite/gnat2goto/tests/no_return_returns/test.py
We insert an explicit check at the end of the function (marked by the pragma). The check is just a wrapper for `assert(false)`. Includes a check.
=> Handle no return pragma

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/tree_walk.adb
As these units will be analysed when "withed" they are not analysed
as a stand-alone compilation unit.
=> Handle compilation units that are package or subprogram declarations.

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/discriminated_record/discriminated_record.adb, testsuite/gnat2goto/tests/discriminated_record/test.out
the test is now marked as failing.
=> Discriminated record formation is broken

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/arrays.ads, gnat2goto/driver/range_check.adb, gnat2goto/driver/range_check.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/arrays_access/test.out, testsuite/gnat2goto/tests/arrays_assign_nonoverlap/test.out, testsuite/gnat2goto/tests/arrays_attributes_static/test.out, testsuite/gnat2goto/tests/arrays_concat/test.out, testsuite/gnat2goto/tests/arrays_constraints/test.out, testsuite/gnat2goto/tests/arrays_index/test.out, testsuite/gnat2goto/tests/arrays_index_enum/test.out, testsuite/gnat2goto/tests/discriminated_record/test.out, testsuite/gnat2goto/tests/enum_in_param/test.out, testsuite/gnat2goto/tests/index_check/main.adb, testsuite/gnat2goto/tests/index_check/test.out, testsuite/gnat2goto/tests/index_check/test.py, testsuite/gnat2goto/tests/private_type_dec_array/test.out, testsuite/gnat2goto/tests/rhs_array_assign/test.out
when parsing the `n_indexed_component` node. Using the same methods as for the
range check, i.e. first_index < index < last_index. Includes a test.
=> Add index check

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/muen-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb, gnat2goto/ireps/irep_specs/null_pointer.json, testsuite/gnat2goto/tests/null_pointer/null_pointer.adb, testsuite/gnat2goto/tests/null_pointer/test.out, testsuite/gnat2goto/tests/null_pointer/test.py
Note that as of now this only adds support for the expression itself,
support for access types themselves is still missing, so this won’t yet
work in cases where we use access types in a nontrivial way.
=> Add support for null pointer expression

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/access-to-object/main.adb, testsuite/gnat2goto/tests/access-to-object/test.out, testsuite/gnat2goto/tests/access-to-object/test.py, testsuite/gnat2goto/tests/null_pointer/test.out
by simply creating a pointer-to type.
Note: this somehow was not triggered by our existing primitive-pointer test (which had `int*`).
=> Add support to access-to-object type

testsuite/gnat2goto/tests/address_clause/test.out, testsuite/gnat2goto/tests/arrays_access/test.out, testsuite/gnat2goto/tests/arrays_assign_nonoverlap/test.out, testsuite/gnat2goto/tests/arrays_attributes_dynamic/test.out, testsuite/gnat2goto/tests/arrays_attributes_static/test.out, testsuite/gnat2goto/tests/arrays_concat/test.out, testsuite/gnat2goto/tests/arrays_constraints/test.out, testsuite/gnat2goto/tests/arrays_index/test.out, testsuite/gnat2goto/tests/arrays_index_enum/test.out, testsuite/gnat2goto/tests/arrays_range/test.out, testsuite/gnat2goto/tests/arrays_write_element/test.out, testsuite/gnat2goto/tests/attrib_address/test.out, testsuite/gnat2goto/tests/enum_in_param/test.out, testsuite/gnat2goto/tests/expanded_name_subtype_indication/test.out, testsuite/gnat2goto/tests/if_integer/test.out, testsuite/gnat2goto/tests/in_expression/test.out, testsuite/gnat2goto/tests/index_check/test.out, testsuite/gnat2goto/tests/package_type/test.out, testsuite/gnat2goto/tests/representation_clause_component_size/test.out, testsuite/gnat2goto/tests/rhs_array_assign/test.out
Brings in diffblue/cbmc#5214
Previously propreties that differed only by name would be in a undefined order. Now they are sorted first by name, then by number. Expected output is updated accordingly.
=> Update tests with ordered properties

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/gnat2goto_itypes.adb
Small fix to make sure that if we get an unknown kind of Itype we know which one it is.
=> Display Ekind of unhandled Itypes in Do_Itype_Definition

experiments/golden-results/SPARK-tetris-summary.txt, experiments/golden-results/StratoX-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/gnat2goto_itypes.adb, gnat2goto/driver/gnat2goto_itypes.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/arrays_declaration_failure1/arrays_declaration_failure1.adb, testsuite/gnat2goto/tests/arrays_declaration_failure1/test.opt, testsuite/gnat2goto/tests/arrays_declaration_failure1/test.out, testsuite/gnat2goto/tests/arrays_declaration_failure2/arrays_declaration_failure2.adb, testsuite/gnat2goto/tests/arrays_declaration_failure2/test.opt, testsuite/gnat2goto/tests/arrays_declaration_failure2/test.out, testsuite/gnat2goto/tests/arrays_multidimensional_declaration_failure1/test.opt, testsuite/gnat2goto/tests/function_pointer/test.out, testsuite/gnat2goto/tests/procedure_pointer/test.out
This PR adds support for declaring Itypes (implicit types) for array declarations.
=> Declare implicit array types

.travis.yml, testsuite/gnat2goto/tests/function_pointer/test.out, testsuite/gnat2goto/tests/procedure_pointer/test.out
The AdaCore website seems to have migrated to a new AWS S3 based
storage so the older URLs.  I have checked and files have the same
SHA1 as before.
=> Change the URLs for GNAT GPL 2016 and GNATCOL 2016 in .travis.yml

gnat2goto/driver/range_check.adb, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/enum_range_checks/enums.adb, testsuite/gnat2goto/tests/enum_range_checks/test.out, testsuite/gnat2goto/tests/enum_range_checks/test.py, testsuite/gnat2goto/tests/function_pointer/test.out, testsuite/gnat2goto/tests/procedure_pointer/test.out
Use enumeration literal position as their value rather than their representation value.  Using their position maintains an order relation between the literals of an enumeration whereas using their representation value does not necessarily.  If, in future, a representation value is needed (for low level I/O) a function could be provided to obtain the representation from an enumeration literals position.  Such a function exists in gnat but is possible a goto equivalent may be needed.
=> Use enum pos

gnat2goto/driver/tree_walk.adb
Gnat2goto does not currently use the information in freeze nodes.  It used more by the front-end.
Since the are not used ignore them.
We may have to revisit this decision when package initialisation is considered.
=> Ignore Freeze nodes.  They are not currently required by gnat2goto.

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/Tokeneer-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/vct-summary.txt, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/fixed_array_address_model/test.out, testsuite/gnat2goto/tests/more_pragmas/more_pragmas.adb, testsuite/gnat2goto/tests/more_pragmas/test.out, testsuite/gnat2goto/tests/more_pragmas/test.py, testsuite/gnat2goto/tests/record_address_model/test.out, testsuite/gnat2goto/tests/simple_address_model/test.out, testsuite/gnat2goto/tests/u_array_address_model/test.out
Ignore pragmas Compile_Time_Warning, Linker_Options, and partially ignore pragma Suppress_Initialization.
Linker_Options may be processed in a later release if symtab2gb was to have more options.
Suppress_Initialization is only ignored if it is applied to an array type or scalar type which has no default value aspect.  Otherwise it is still reported as unsupported.
It could be improved with more work so that it could be ignored in more cases or actually to change the initialisation code.  But for the moment it clears all but one instance in the CI tests.
=> More pragmas

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/UKNI-Information-Barrier-summary.txt, experiments/golden-results/ksum-summary.txt, experiments/golden-results/libkeccak-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/asvat-modelling.adb, gnat2goto/driver/asvat-modelling.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/intrinsic/test.out, testsuite/gnat2goto/tests/no_corresponding_spec/test.out, testsuite/gnat2goto/tests/nondet_enum_sub/nondet_enum_sub.adb, testsuite/gnat2goto/tests/nondet_enum_sub/test.out, testsuite/gnat2goto/tests/nondet_enum_sub/test.py, testsuite/gnat2goto/tests/nondet_function/nondet_function.adb, testsuite/gnat2goto/tests/nondet_function/test.out, testsuite/gnat2goto/tests/nondet_function/test.py, testsuite/gnat2goto/tests/nondet_int/nondet_int.adb, testsuite/gnat2goto/tests/nondet_int/test.opt, testsuite/gnat2goto/tests/nondet_int/test.py
Provide of specifying ASVAT models via an annotation.
Current models are Nondet_Function and In_Type_Function.
See header of ASVAT.Modelling (asvat-modelling.ads).
=> Nondet model

gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/record_aggregates/record_aggregates.adb, testsuite/gnat2goto/tests/record_aggregates/test.opt, testsuite/gnat2goto/tests/record_aggregates/test.out, testsuite/gnat2goto/tests/record_aggregates/test.py, testsuite/gnat2goto/tests/record_aggregates_box/record_aggregates_box.adb, testsuite/gnat2goto/tests/record_aggregates_box/test.opt, testsuite/gnat2goto/tests/record_aggregates_box/test.out, testsuite/gnat2goto/tests/record_aggregates_box/test.py
This patch fixes two issues which cause gnat2goto to fail when processing the example pub/sub system.
They both related to record aggregates, particularly when the record is discriminated.
The first issue is fixed by using the component name string rather than its node id as the front-end seems to frequently rewrite such nodes giving them a different node id.
The other failure, due to an unsatisfied precondition is solved by relaxing the precondition to allow I_Code_Assert Ireps.
The patch does not solve all the problems, i.e. others => <> in a record still causes gnat2goto to fail a precondition and the symbol table generated seems to be very large and cbmc fails when run on the symbol table.  However, it does solve the immediate problem of the gnat2goto failures when processing the …
=> Record aggregates

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/subprog_components/func_components.adb, testsuite/gnat2goto/tests/subprog_components/test.opt, testsuite/gnat2goto/tests/subprog_components/test.out, testsuite/gnat2goto/tests/subprog_components/test.py
Access to subprogram objects can be components of an array or record (or even a result of a function).
This patch handles calls to such objects.
=> Func components

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/access_subprog_access_param/access_subprog_access_param.adb, testsuite/gnat2goto/tests/access_subprog_access_param/test.opt, testsuite/gnat2goto/tests/access_subprog_access_param/test.out, testsuite/gnat2goto/tests/access_subprog_access_param/test.py
Access to subprogram type declarations may have access parameters.
Use a common routine (Do_Subprogram_Specification) for subprogram parameters which handles access parameters.
Do_Subprogram_Specification extended to handle access subprogram definitions.
=> Access subprog access param

experiments/golden-results/StratoX-summary.txt, experiments/golden-results/libsparkcrypto-summary.txt, experiments/golden-results/muen-summary.txt, gnat2goto/driver/arrays.adb, gnat2goto/driver/asvat-address_model.ads, gnat2goto/driver/asvat-modelling.adb, gnat2goto/driver/asvat-size_model.adb, gnat2goto/driver/asvat-size_model.ads, gnat2goto/driver/asvat.ads, gnat2goto/driver/driver.adb, gnat2goto/driver/goto_utils.ads, gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/iss_131_implicit_packing/iss_131.adb, testsuite/gnat2goto/tests/iss_131_implicit_packing/test.out, testsuite/gnat2goto/tests/iss_131_rational/test.out, testsuite/gnat2goto/tests/iss_131_use_VADS/test.out, testsuite/gnat2goto/tests/iss_131_vanilla/iss_131.adb, testsuite/gnat2goto/tests/iss_131_vanilla/test.out
First stage of an implementation to record and publish (via attribute 'Size) the ASVAT model size of an object as opposed to its code size.
=> Model size

testsuite/gnat2goto/tests/arrays/test.opt, testsuite/gnat2goto/tests/attrib_size_object/test.opt, testsuite/gnat2goto/tests/attrib_size_object/test.out, testsuite/gnat2goto/tests/attrib_size_simple/test.opt, testsuite/gnat2goto/tests/attrib_size_simple/test.out, testsuite/gnat2goto/tests/do_in/test.opt, testsuite/gnat2goto/tests/do_in/test.out, testsuite/gnat2goto/tests/loop_array_range/test.opt, testsuite/gnat2goto/tests/loop_array_range/test.out, testsuite/gnat2goto/tests/nondet_int/test.opt, testsuite/gnat2goto/tests/nondet_int/test.out, testsuite/gnat2goto/tests/object_declaration_statement_bounds_crashing/test.opt, testsuite/gnat2goto/tests/object_declaration_statement_bounds_crashing/test.out, testsuite/gnat2goto/tests/op_concat/test.opt, testsuite/gnat2goto/tests/representation_clause_component_size_change/test.opt, testsuite/gnat2goto/tests/representation_clause_component_size_change/test.out, testsuite/gnat2goto/tests/reverse/test.opt, testsuite/gnat2goto/tests/reverse/test.out, testsuite/gnat2goto/tests/separate_subprog_assert_check/test.opt, testsuite/gnat2goto/tests/separate_subprog_assert_check/test.out, testsuite/gnat2goto/tests/subpackage_local_initialisers/test.opt, testsuite/gnat2goto/tests/subpackage_local_initialisers/test.out
Updated the following test folders
arrays						- updated test.opt
attrib_size_object				- added test.out removed test.opt
attrib_size_simple				- added test.out removed test.opt
do_in						- replaced test.out removed test.opt
loop_array_range				- added test.out removed test.opt
nondet_int					- replaced test.out removed test.opt
object_declaration_statement_bounds_crashing	- added test.out removed test.opt
op_concat					- updated test.opt
representation_clause_component_size_change	- added test.out removed test.opt
reverse						- replaced test.out removed test.opt
separate_subprog_assert_check			- replaced test.out removed test.opt
subpackage_local_initialisers			- replaced test.out removed test.opt
=> fixes for issue #108 to update XFAIL state

gnat2goto/driver/tree_walk.adb, testsuite/gnat2goto/tests/recursive_datatype/rec_data.adb, testsuite/gnat2goto/tests/recursive_datatype/test.out, testsuite/gnat2goto/tests/recursive_datatype/test.py
The declaration of a recursive data type was causing infinite recursion and a stack overflow.
This change addresses this issue for simple recursive data type declarations.
=> Rec data/working

experiments/golden-results/StratoX-summary.txt, gnat2goto/driver/driver.adb
If you need the verbose mode, try running:
$ jq . whatever.json_symtab
=> Reduce the size of JSON files by printing in compact mode

gnat2goto/driver/driver.adb, gnat2goto/driver/gnatcoll-json-file.adb, gnat2goto/driver/gnatcoll-json-file.ads
It removes the bottleneck of creating a large string containing
the text version of the JSON Symbol before outputting the string
to the json_symtab file.
A JASON_Value Write procedure has been created in a child package
of GNATCOLL.JASON (GNATCOLL.JSON.File) which outputs the text version
of a JSON_Value directly to a given text file.
Further efficiencies may be possible by disposing of unwanted fields of the symbol table during
conversion of the symbol table to JSON rather than generating a new symbol table without
the unwanted fields.  If this necessary, I think this should be handled as new issue.
Similarly, but more difficult, one could consider outputting the JSON format directly from
the symbol table without using GNATCOLL.JSON.
This could avoid building a large in memory JSON …
=> This change addresses issue 314.
