diffblue/gnat2goto

gnat2goto/driver/tree_walk.adb
gnat2goto/examples/pragma_loop_invariant.adb
gnat2goto/examples/pragma_loop_invariant_simple.adb

Generate asserts for loop invariants

Generate asserts for loop invariants

---

gnat2goto/driver/driver.adb
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/long_integer/test_long_integer.adb
testsuite/gnat2goto/tests/loops/loops.adb

This is only relevant for the last 3 commits. WIll be rebased once the dependent PR (https://github.com/diffblue/gnat2goto/pull/25) gets merged.

Fix regression tests and start supporting more expression types.

---

gnat2goto/ireps/ireps_generator.py

Remove unused variables and imports
Add missing default arguments
Part of a bigger refactoring process.

Refactor ireps_generator.py

---

gnat2goto/ireps/ireps_generator.py

The real diff is in the last commit. What changed is I added a class and moved the big functions inside as members functions. Filtering out the whitespace should make it easy to see the changes.

Refactor continued

---

gnat2goto/ireps/ireps_generator.py

The big part of refactoring the file. I've managed to break it down to multiple commits with minimal changes to each one.

Refactor continued2

---

gnat2goto/ireps/ireps_generator.py

It doesn't cause any bugs yet but a potential change in the type hierarchy could cause one. Found it by testing a hypothesis that was ammending the type hierarchy.
The actual change is the last commit.

Subclass leaf node

---

gnat2goto/driver/tree_walk.adb

This PR will identify unsupported features of the Ada to GOTO translation and replace occurrences of failure-based error-handling (exceptions, pre/post-conditions, assertions, etc.) with suitable report log.

Report unsupported features instead of failing

---

experiments/collect_unsupported.cpp
experiments/list_unsupported.sh
gnat2goto/driver/tree_walk.adb
gnat2goto/ireps/follow.ads

Created by running gnat2goto on public repositories and tracking what failed.
Thus the selection is fairly random.

Additional reporting of unsupported features

---

gnat2goto/driver/binary_to_hex.adb
gnat2goto/driver/binary_to_hex.ads
gnat2goto/driver/tree_walk.adb
gnat2goto/ireps/irep_specs/symbol_type.json
gnat2goto/unit/binary_to_hex_tests.adb
gnat2goto/unit/binary_to_hex_tests.ads
gnat2goto/unit/unit_tests.adb
testsuite/gnat2goto/tests/divide/divide.adb
testsuite/gnat2goto/tests/long_integer/test.opt

Adds a binary to hex function and makes gnat2goto use it. Function itself is easy enough and is completely reviewable, I'm not so sure if the changes in driver and tree_walk are the right changes, hence the WIP tag

Make bitvector output hex

---

gnat2goto/driver/driver.adb
testsuite/gnat2goto/tests/enum/enum.adb
testsuite/gnat2goto/tests/enum/test.out
testsuite/gnat2goto/tests/enum/test.py

Enhance enum support so that values can now be compared to each other.

Fix enum support

---

gnat2goto/driver/goto_utils.adb
gnat2goto/driver/goto_utils.ads
gnat2goto/driver/tree_walk.adb
gnat2goto/ireps/ireps-follow_irep.adb
gnat2goto/ireps/ireps-remove_bounds.adb

This PR is a preparation/clean-up for array slicing, concatenation, and assignment.

Refactor tree-walk for arrays

---

experiments/list_unsupported.sh

In accordance to ADA-249 (and ASVAT issue #33) we add inclusion of some Ada
paths as well as checking that gnat2goto can list features. We also fail
early when gnat2goto fails (in an unexpected way).

Make unsupported feature listing script more robust

---

gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/private_type_decl/private_type_decl.adb
testsuite/gnat2goto/tests/private_type_decl/private_type_decl.ads
testsuite/gnat2goto/tests/private_type_decl/test.opt
testsuite/gnat2goto/tests/private_type_decl/test.py

We don't support this. Martin thinks Trevor is preparing the support.

Add failing test for private type declarations

---

gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/op_or/op_or.adb
testsuite/gnat2goto/tests/op_or/test.out
testsuite/gnat2goto/tests/op_or/test.py

This PR adds support for the logical `or` operator, and a test for it in the testsuite.

Add support for Logical Or Operator

---

gnat2goto/driver/ureal_to_binary.adb
gnat2goto/unit/floating_point_tests.adb
testsuite/gnat2goto/tests/floating_point_literals/floating_point_literals.adb
testsuite/gnat2goto/tests/floating_point_literals/test.opt
testsuite/gnat2goto/tests/floating_point_literals/test.out

This fixes the immediate issue in https://github.com/diffblue/gnat2goto/issues/149
However, this is still a hackjob of an implementation and needs to be redone from the ground up.

Fix floating point conversion

---

gnat2goto/driver/tree_walk.adb
gnat2goto/driver/ureal_to_binary.adb
testsuite/gnat2goto/tests/real_literal/real_literal.adb
testsuite/gnat2goto/tests/real_literal/test.opt
testsuite/gnat2goto/tests/real_literal/test.out

The buffer for the integer part was not large enough. Test case was updated and
extended.

Fix large real literals

---

experiments/list_unsupported.sh

* Summarization/collation of compilation failures
* Improvements to redacting
* Cleanup to make the above possible

Further improvements to list_unsupported.sh

---

gnat2goto/driver/binary_to_hex.adb
gnat2goto/driver/binary_to_hex.ads
gnat2goto/driver/uint_to_binary.adb
gnat2goto/unit/uint_to_binary_tests.adb
gnat2goto/unit/uint_to_binary_tests.ads
gnat2goto/unit/unit_tests.adb

* Sizes no longer have to be a power of two
* Also refactors the uint_to_binary conversion a lot, it is shorter and should
also be easier to understand now
* Also works with negative numbers now

Make uint to (hex or binary) bitvector conversions work better

---

gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/attributes_continuous/attributes_continuous.adb
testsuite/gnat2goto/tests/attributes_continuous/test.opt
testsuite/gnat2goto/tests/attributes_discrete/attributes_discrete.adb
testsuite/gnat2goto/tests/attributes_discrete/test.out

Pos, Val, Pred, and Succ. Works for discrete, fails for continuous. Succeeding and failing tests are included.

Attributes for discrete types

---

testsuite/gnat2goto/tests/attributes_continuous/test.py
testsuite/gnat2goto/tests/attributes_discrete/test.out
testsuite/gnat2goto/tests/attributes_discrete/test.py
testsuite/gnat2goto/testsuite.py

* attributes test didn't include test.py, and one had wrong test.out
* our testsuite didn't catch that, so I also changed it to detect invalid tests

Fix broken tests

---

experiments/golden-results/SPARK-tetris-summary.txt
experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/ksum-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/tree_walk.adb

In Process_Declaration and Process_Statement.

Report unsupported instead of warning

---

gnat2goto/driver/range_check.adb
gnat2goto/driver/range_check.ads

Trivial PR. Includes have been tidied for improved ordering (ada packages, gnat packages, gnat2goto packages).

Range package improved categorization and order of included packages

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/type_modular_arithmetic/modular_type.adb
testsuite/gnat2goto/tests/type_modular_arithmetic/test.out
testsuite/gnat2goto/tests/type_modular_arithmetic/test.py

Simple function that handles plus, minus, times, and divide for modular types. This PR extends the existing test for modular types.
Plese do not review the first commit here: it's the prerequisite PR #198.

Modular arithmetic peano operators

---

experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/record_extension/record_init.adb
testsuite/gnat2goto/tests/record_extension/test.opt
testsuite/gnat2goto/tests/record_extension/test.py

Also a better reporting of this and other derived type definition. Resolving
this would probably require us to support tagged types and by extension the
whole object-oriented part of Ada.

Failing test for record extension

---

testsuite/gnat2goto/tests/type_modular/modular.adb
testsuite/gnat2goto/tests/type_modular/test.out

This is #205, reworked after a suggestion from Hannes.

Add an extra case to the modular type test.

---

experiments/golden-results/SPARK-tetris-summary.txt
experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/ksum-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/tree_walk.adb

Case analysis and ignoring those suggested in https://github.com/martin-cs/ASVAT/issues/63. Still missing is handling `volatile` and `machine attribute`.

Pragmas in declarations (ignore-able cases)

---

experiments/collect_unsupported.cpp

I fully expect this to fail CI because I think it will change what the golden results look like - I just want to get a run through CI to see how bad it is, and also get @xbauch views on the code change.

Fix up performance issue in CollectUnsupported

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
gnat2goto/driver/tree_walk.ads
testsuite/gnat2goto/tests/expanded_name_subtype_indication/base.ads
testsuite/gnat2goto/tests/expanded_name_subtype_indication/test.adb
testsuite/gnat2goto/tests/expanded_name_subtype_indication/test.out
testsuite/gnat2goto/tests/expanded_name_subtype_indication/test.py

so we extend the case analysis.

Subtype indication can be expanded name as well

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/tree_walk.adb

Ignore one more pragma, as per https://github.com/martin-cs/ASVAT/issues/63#issuecomment-490908676

Pragma implementation defined

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/arrays.adb
gnat2goto/driver/arrays.ads
gnat2goto/driver/goto_utils.adb
gnat2goto/driver/goto_utils.ads
gnat2goto/driver/range_check.adb
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/arrays_index_enum/test.adb
testsuite/gnat2goto/tests/arrays_index_enum/test.out
testsuite/gnat2goto/tests/arrays_index_enum/test.py

The second commit needs some cleaning.

Allow enums as array indices

---

gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/intrinsic/test.out
testsuite/gnat2goto/tests/intrinsic/test.py
testsuite/gnat2goto/tests/intrinsic/use_import.adb

This PR replace PR #243, the same changes but with a clean history from a new rebase.

New handle intrinsic

---

.travis.yml
experiments/list_unsupported.sh

This PR is probably easier to review commit-by-commit, rather than as a whole diff. There is only a small amount of real change, but some code has moved around making the whole diff for the PR look more messy than it really is.

List unsupported user help

---

experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/loop_in_custom_type/test.adb
testsuite/gnat2goto/tests/loop_in_custom_type/test.out
testsuite/gnat2goto/tests/loop_in_custom_type/test.py

In case that type is a range type. For example `for x in range_type` where `range_type = from
.. to`. Includes a test.

Implement looping over user-type

---

.travis.yml
experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/UKNI-Information-Barrier-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/expanded_name/expanded_name.adb
testsuite/gnat2goto/tests/expanded_name/test.out
testsuite/gnat2goto/tests/expanded_name/test.py
testsuite/gnat2goto/tests/expanded_name/withed_package.ads

Trevor's PR #268 will slightly less commits.

Fix handling expanded name

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/back_end.adb

Rebase of Trevor's enabling ali files

---

experiments/golden-results/SPARK-tetris-summary.txt
experiments/golden-results/StratoX-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/subpackage/other.ads
testsuite/gnat2goto/tests/subpackage/test.adb
testsuite/gnat2goto/tests/subpackage/test.out
testsuite/gnat2goto/tests/subpackage/test.py

during process declarations, using the same procedure we already had for
package-declarations. Includes a test.

Process sub-packages

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/goto_utils.adb
gnat2goto/driver/goto_utils.ads

Continuation of https://github.com/diffblue/gnat2goto/pull/285

Refactor/remove new irep in goto_utils

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/goto_utils.adb
gnat2goto/driver/goto_utils.ads
gnat2goto/driver/tree_walk.adb

This wraps up the "refactoring tree walk to remove used of New_Irep" saga

Refactor/remove new irep from tree walk part 3 (final)

---

gnat2goto/driver/gnat2goto_itypes.adb

Apologies, missed these two apparently

Remove New_Irep from gnat2goto.itypes

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/null_statement_declaration/extra_package.adb
testsuite/gnat2goto/tests/null_statement_declaration/extra_package.ads
testsuite/gnat2goto/tests/null_statement_declaration/generic_package.ads
testsuite/gnat2goto/tests/null_statement_declaration/test.out
testsuite/gnat2goto/tests/null_statement_declaration/test.py

Since this is a null-statement as a declaration, I'm not sure how to reproduce it.

Null-statement ignored

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/ksum-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb

Some extra ignores

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb

Report which attribute is not recognised rather than reporting "unknown attribute"
Golden results have been updated.

Report attrib

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/ksum-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/attrib_address/attrib_address.adb
testsuite/gnat2goto/tests/attrib_address/test.out
testsuite/gnat2goto/tests/attrib_address/test.py

Handle X'Address attributes in expressions.
A simple model is used for ASVAT; return Address_Of, the same as X'Access.

Do address

---

testsuite/gnat2goto/tests/absolute/test.out
testsuite/gnat2goto/tests/absolute_float/test.out
testsuite/gnat2goto/tests/arrays_access/test.out
testsuite/gnat2goto/tests/arrays_assign_nonoverlap/test.out
testsuite/gnat2goto/tests/arrays_attributes_dynamic/test.out
testsuite/gnat2goto/tests/arrays_attributes_static/test.out
testsuite/gnat2goto/tests/arrays_concat/test.out
testsuite/gnat2goto/tests/arrays_index/test.out
testsuite/gnat2goto/tests/arrays_index_enum/test.out
testsuite/gnat2goto/tests/arrays_range/test.out
testsuite/gnat2goto/tests/arrays_write_element/test.out
testsuite/gnat2goto/tests/assertion_pretty_printing/test.out
testsuite/gnat2goto/tests/attrib_address/test.out
testsuite/gnat2goto/tests/divide_by_zero/test.out
testsuite/gnat2goto/tests/enum_in_param/test.out
testsuite/gnat2goto/tests/generics/test.out
testsuite/gnat2goto/tests/if_integer/test.out
testsuite/gnat2goto/tests/in_expression/test.out
testsuite/gnat2goto/tests/index_check/test.out
testsuite/gnat2goto/tests/mixed_parameters/test.out
testsuite/gnat2goto/tests/op_or_else/test.out
testsuite/gnat2goto/tests/pragma_machine_attribute/test.out
testsuite/gnat2goto/tests/procedure_pointer/test.out
testsuite/gnat2goto/tests/representation_clause_component_size/test.out
testsuite/gnat2goto/tests/rhs_array_assign/test.out
testsuite/gnat2goto/tests/statement_new_block_N_Block_Statement/test.out
testsuite/gnat2goto/tests/type_modular_arithmetic/test.out
testsuite/gnat2goto/tests/unary_minus_overflow/test.out

and update the test output ordering.

Bump CBMC to develop

---

testsuite/gnat2goto/tests/ukni_loop_parameter_specification/test.adb
testsuite/gnat2goto/tests/ukni_loop_parameter_specification/test.out
testsuite/gnat2goto/tests/ukni_loop_parameter_specification/test.py

* tests/ukni_loop_parameter_specification
Add test.

Add test for N_Loop_Parameter_Specification #28

---

gnat2goto/COMPILING.md
testsuite/gnat2goto/README.md

Just a couple of things that caused me to pause when getting this compiling.

Make the compiling steps a little more explicit

---

testsuite/gnat2goto/tests/use_package_declaration/test.ads
testsuite/gnat2goto/tests/use_package_declaration/test.out
testsuite/gnat2goto/tests/use_package_declaration/test.py
testsuite/gnat2goto/tests/use_package_declaration/use_package.adb

* testsuite/gnat2goto/tests/use_package_declaration/
Add test.

add test where Process_Declaration handles N_Use_Package_Clause #97

---

experiments/golden-results/StratoX-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/access_parameter/access_parameter.adb
testsuite/gnat2goto/tests/access_parameter/test.out
testsuite/gnat2goto/tests/access_parameter/test.py

Support subprogram formal access parameters.

Access parameters

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/range_check.ads

A term was missing from a precondition which should have been included with PR #337.

Missing from precondition

---

testsuite/gnat2goto/tests/nonliteral_bound/nonliterals.adb
testsuite/gnat2goto/tests/nonliteral_bound/test.out
testsuite/gnat2goto/tests/nonliteral_bound/test.py

rebased branch spanners/nonliteral_bound PR #334 onto the latest master.
added additional test for E_Signed_Integer_Subtype

Nonliteral bounds

---

experiments/golden-results/StratoX-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/pragma_atomic/pragma_atomic.adb
testsuite/gnat2goto/tests/pragma_atomic/test.out
testsuite/gnat2goto/tests/pragma_atomic/test.py

Added a test for pragma Atomic and Atomic_Components.
updated gnat2goto to ignore the pragmas rather than report unsupported.

added test case and updated code for pragma atomic

---

experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/priv_type_aggregates/priv_typ_aggregate.adb
testsuite/gnat2goto/tests/priv_type_aggregates/test.out
testsuite/gnat2goto/tests/priv_type_aggregates/test.py

This PR replaces PR #367 with a different branch because of the inconsistent merges discussed on PR #367.
This change addresses the problem described in Issue #132 from Do_Aggrgate_Literal.
It also resolves a problem described in Issue #52.
PR #367 is no closed.

Priv aggr/final

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/range_check.ads

code fix for gnat crash in range_check.ads pre condition

fix gnat crash

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/arrays.adb
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/array_others_buffer/test.adb
testsuite/gnat2goto/tests/array_others_buffer/test.opt
testsuite/gnat2goto/tests/array_others_buffer/test.py

correction for crashes due to pre condition for Do_Expression

Do expression failure

---

experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
gnat2goto/driver/asvat-address_model.adb
gnat2goto/driver/asvat-modelling.adb
gnat2goto/driver/asvat-modelling.ads
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/with_exception/test.out

Handling of unchecked_conversion
Value validated after conversion.
Currently not all types are validated,including pointer types, Boolean types and array types.

Unchecked conversion ready

---

experiments/golden-results/SPARK-tetris-summary.txt
experiments/golden-results/StratoX-summary.txt
experiments/golden-results/Tokeneer-summary.txt
experiments/golden-results/ksum-summary.txt
experiments/golden-results/libkeccak-summary.txt
experiments/golden-results/libsparkcrypto-summary.txt
experiments/golden-results/muen-summary.txt
experiments/golden-results/vct-summary.txt
gnat2goto/driver/tree_walk.adb
testsuite/gnat2goto/tests/ada_text_io/test.out
testsuite/gnat2goto/tests/with_exception/test.out

Suppressed unsupported feature messages for pragmas which have little or no relevance to ASVAt.

Pragma tidy
